### ISSUE TITLE
通过frp内网穿透结合nginx反向代理后无法登陆

### ISSUE THREAD

**Issue by lsylx** [cloudreve/Cloudreve#1423]
frp客户端在这台机器上 配置80 443端口
按照Docs的方法在nginx中配置好反向代理后无法登陆
配置文档如下
```
server
{
    listen 80;
    listen 443 ssl http2;
    server_name liuson.cn www.liuson.cn;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/liuson.cn/;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    ssl_certificate    /www/server/panel/vhost/cert/liuson.cn/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/liuson.cn/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497  https://$host$request_uri;
		#SSL-END

    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END

    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-81.conf;
    #PHP-INFO-END

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/liuson.cn.conf;
    #REWRITE-END

    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }

    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null;
    }
    access_log  /www/wwwlogs/liuson.cn.log;
    error_log  /www/wwwlogs/liuson.cn.error.log;
}
```
控制台显示
```
[Info]    2022-08-01 17:10:08 开始监听 :5212
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :5212
2022/08/01 17:10:12 [sessions] ERROR! securecookie: the value is not valid

(/home/runner/work/Cloudreve/Cloudreve/models/setting.go:71) 
[2022-08-01 17:10:12]  [0.84ms]  SELECT * FROM "settings"  WHERE "settings"."deleted_at" IS NULL AND ((name IN ('captcha_IsShowHollowLine','captcha_IsShowNoiseDot','captcha_IsShowNoiseText','captcha_IsShowSlimeLine','captcha_IsShowSineLine')))  
[5 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/setting.go:47) 
[2022-08-01 17:10:12]  [0.22ms]  SELECT * FROM "settings"  WHERE "settings"."deleted_at" IS NULL AND ((name = 'captcha_height')) ORDER BY "settings"."id" ASC LIMIT 1  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/setting.go:47) 
[2022-08-01 17:10:12]  [0.20ms]  SELECT * FROM "settings"  WHERE "settings"."deleted_at" IS NULL AND ((name = 'captcha_width')) ORDER BY "settings"."id" ASC LIMIT 1  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/setting.go:47) 
[2022-08-01 17:10:12]  [0.17ms]  SELECT * FROM "settings"  WHERE "settings"."deleted_at" IS NULL AND ((name = 'captcha_mode')) ORDER BY "settings"."id" ASC LIMIT 1  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/setting.go:47) 
[2022-08-01 17:10:12]  [0.17ms]  SELECT * FROM "settings"  WHERE "settings"."deleted_at" IS NULL AND ((name = 'captcha_ComplexOfNoiseText')) ORDER BY "settings"."id" ASC LIMIT 1  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/setting.go:47) 
[2022-08-01 17:10:12]  [0.18ms]  SELECT * FROM "settings"  WHERE "settings"."deleted_at" IS NULL AND ((name = 'captcha_ComplexOfNoiseDot')) ORDER BY "settings"."id" ASC LIMIT 1  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/setting.go:47) 
[2022-08-01 17:10:12]  [0.19ms]  SELECT * FROM "settings"  WHERE "settings"."deleted_at" IS NULL AND ((name = 'captcha_CaptchaLen')) ORDER BY "settings"."id" ASC LIMIT 1  
[1 rows affected or returned ] 
[GIN] 2022/08/01 - 17:10:12 | 200 |   19.869182ms |       127.0.0.1 | GET      "/api/v3/site/captcha"

(/home/runner/work/Cloudreve/Cloudreve/models/setting.go:71) 
[2022-08-01 17:10:15]  [0.75ms]  SELECT * FROM "settings"  WHERE "settings"."deleted_at" IS NULL AND ((name IN ('login_captcha','captcha_type','captcha_ReCaptchaSecret','captcha_TCaptcha_SecretId','captcha_TCaptcha_SecretKey','captcha_TCaptcha_CaptchaAppId','captcha_TCaptcha_AppSecretKey')))  
[7 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/user.go:153) 
[2022-08-01 17:10:15]  [0.37ms]  SELECT * FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((email = 'shawn@liuson.cn')) ORDER BY "users"."id" ASC LIMIT 1  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/user.go:153) 
[2022-08-01 17:10:15]  [0.50ms]  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL AND (("id" IN (1))) ORDER BY "groups"."id" ASC  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/policy.go:92) 
[2022-08-01 17:10:15]  [0.35ms]  SELECT * FROM "policies"  WHERE "policies"."deleted_at" IS NULL AND (("policies"."id" = 1)) ORDER BY "policies"."id" ASC LIMIT 1  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/tag.go:44) 
[2022-08-01 17:10:15]  [0.28ms]  SELECT * FROM "tags"  WHERE "tags"."deleted_at" IS NULL AND ((user_id = 1))  
[0 rows affected or returned ] 
[GIN] 2022/08/01 - 17:10:15 | 200 |    3.567839ms |       127.0.0.1 | POST     "/api/v3/user/session"

(/home/runner/work/Cloudreve/Cloudreve/models/user.go:139) 
[2022-08-01 17:10:15]  [0.34ms]  SELECT * FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((status = 0) AND ("users"."id" = 1)) ORDER BY "users"."id" ASC LIMIT 1  
[1 rows affected or returned ] 

(/home/runner/work/Cloudreve/Cloudreve/models/user.go:139) 
[2022-08-01 17:10:15]  [0.27ms]  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL AND (("id" IN (1))) ORDER BY "groups"."id" ASC  
[1 rows affected or returned ] 
[GIN] 2022/08/01 - 17:10:15 | 200 |   15.636508ms |       127.0.0.1 | GET      "/api/v3/site/captcha"

```
网页端显示
```
Cannot read properties of undefined (reading 'saveType')
```

尝试在nginx配置文件中添加
```
proxy_cookie_flags ~ nosecure;
```
Linux控制台报错消失，无法登陆依旧

Chrome控制台报错内容如下
```
DevTools 无法加载来源映射：无法解析 https://pan.liuson.cn/static/css/6.d9dc5367.chunk.css.map 的内容：Unexpected token < in JSON at position 0
DevTools 无法加载来源映射：无法解析 https://pan.liuson.cn/static/js/6.d35d1220.chunk.js.map 的内容：Unexpected token < in JSON at position 0
DevTools 无法加载来源映射：无法解析 https://pan.liuson.cn/static/js/main.1e4a2f91.chunk.js.map 的内容：Unexpected token < in JSON at position 0
main.1e4a2f91.chunk.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'saveType')
    at $ (main.1e4a2f91.chunk.js:1:118931)
    at main.1e4a2f91.chunk.js:1:119719
$ @ main.1e4a2f91.chunk.js:1
（匿名） @ main.1e4a2f91.chunk.js:1
Promise.then（异步）
（匿名） @ main.1e4a2f91.chunk.js:1
c @ 6.d35d1220.chunk.js:1
（匿名） @ 6.d35d1220.chunk.js:1
（匿名） @ 6.d35d1220.chunk.js:1
r @ 6.d35d1220.chunk.js:1
l @ 6.d35d1220.chunk.js:1
（匿名） @ 6.d35d1220.chunk.js:1
（匿名） @ 6.d35d1220.chunk.js:1
X @ main.1e4a2f91.chunk.js:1
（匿名） @ main.1e4a2f91.chunk.js:1
6426 @ main.1e4a2f91.chunk.js:1
p @ login:1
6363 @ main.1e4a2f91.chunk.js:1
p @ login:1
f @ login:1
e @ login:1
（匿名） @ main.1e4a2f91.chunk.js:1
```

**Comment by wangxiaoerYah** [comment]
奇了怪了，nginx配置通篇没看见你的proxy配置。配置能贴全吗？
()[https://pkg.go.dev/github.com/gin-gonic/gin#section-readme]这个报错说得是你的反向代理没有传访问IP吧，你的后端收不到ip。
难道说你是自定义前端？也许你可以试试不用自定义前端配置。

我想到的另一个可能是，你用的wifi访问了你的网站，你的网站是解析的你的WiFi的公网ip，然后你相当于你的客户机ip是127.0.0.1，然后你的访问IP不合法了？猜测🌝

**Comment by wangxiaoerYah** [comment]
如果是这样的话你试试不用WiFi访问你的网站。

**Comment by topjohncian** [comment]
你的浏览器中仍是历史版本的静态资源，非最新3.6版本的静态资源

a. 请尝试清除浏览器的缓存
( `F12 Devtools -> Application -> Service Worker -> Unregister` ) 然后 <kbd>Ctrl + F5</kbd> 硬刷新

b. 如果 Cloudreve 目录下有 `statics` 文件夹，请尝试删除它然后重启 Cloudreve，按以上流程再走一遍

**Comment by topjohncian** [comment]
补充：建议删除 nginx 配置中
```
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }

    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null;
    }
```

可能会导致你的静态资源无法自动更新

**Comment by lsylx** [comment]
> 补充：建议删除 nginx 配置中
> 
> ```
> location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
>     {
>         expires      30d;
>         error_log /dev/null;
>         access_log /dev/null;
>     }
> 
>     location ~ .*\.(js|css)?$
>     {
>         expires      12h;
>         error_log /dev/null;
>         access_log /dev/null;
>     }
> ```
> 
> 可能会导致你的静态资源无法自动更新

经过测试有效，非常感谢。

**Comment by topjohncian** [comment]
> 你的浏览器中仍是历史版本的静态资源，非最新3.6版本的静态资源
> 
> a. 请尝试清除浏览器的缓存 ( `F12 Devtools -> Application -> Service Worker -> Unregister` ) 然后 Ctrl + F5 硬刷新
> 
> b. 如果 Cloudreve 目录下有 `statics` 文件夹，请尝试删除它然后重启 Cloudreve，按以上流程再走一遍

> 补充：建议删除 nginx 配置中
> 
> ```
> location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
>     {
>         expires      30d;
>         error_log /dev/null;
>         access_log /dev/null;
>     }
> 
>     location ~ .*\.(js|css)?$
>     {
>         expires      12h;
>         error_log /dev/null;
>         access_log /dev/null;
>     }
> ```
> 
> 可能会导致你的静态资源无法自动更新



Ref: #1265
