### ISSUE TITLE
无法连接已有远程 PostgreSQL 报 EOF

### ISSUE THREAD

**Issue by sxjeru** [cloudreve/Cloudreve#1447]
> V3.5.3  Commit #0e5683b  Pro=false

vps 上用 psql 可正常连接到数据库，但配置后启动 Cloudreve 报以下错误：
```
[Info]    2022-08-19 16:30:09 初始化数据库连接
[Panic]   2022-08-19 16:30:09 连接数据库不成功, EOF
panic: 连接数据库不成功, EOF

goroutine 1 [running]:
github.com/cloudreve/Cloudreve/v3/pkg/util.(*Logger).Panic(0x40001189d0, {0x11c2256, 0x1c}, {0x40004b5b18, 0x1, 0x1})
        /home/runner/work/Cloudreve/Cloudreve/pkg/util/logger.go:74 +0xc4
github.com/cloudreve/Cloudreve/v3/models.Init()
        /home/runner/work/Cloudreve/Cloudreve/models/init.go:60 +0x818
github.com/cloudreve/Cloudreve/v3/bootstrap.Init.func3()
        /home/runner/work/Cloudreve/Cloudreve/bootstrap/init.go:47 +0x20
github.com/cloudreve/Cloudreve/v3/bootstrap.Init({0x40003b26d8, 0x18}, {0x1682140, 0x400008e140})
        /home/runner/work/Cloudreve/Cloudreve/bootstrap/init.go:104 +0x294
main.init.0()
        /home/runner/work/Cloudreve/Cloudreve/main.go:39 +0x3e8
```

使用的数据库服务由 bit.io 提供，数据库中已有其他数据表。

**Comment by cjs520** [comment]
你确定conf.ini写对了?检查一下sql用户
