### ISSUE TITLE
[BUG] 配置文件使用 sqlite 时应用 panic

### ISSUE THREAD

**Issue by mritd** [cloudreve/Cloudreve#550]
### 1、崩溃日志

```sh
cloudreve    |    ___ _                 _
cloudreve    |   / __\ | ___  _   _  __| |_ __ _____   _____
cloudreve    |  / /  | |/ _ \| | | |/ _ | '__/ _ \ \ / / _ \
cloudreve    | / /___| | (_) | |_| | (_| | | |  __/\ V /  __/
cloudreve    | \____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|
cloudreve    |
cloudreve    |    V3.1.1-6-g0115b7c  Commit #0115b7c  Pro=false
cloudreve    | ================================================
cloudreve    |
cloudreve    | [Info]    2020-09-02 13:32:03 初始化数据库连接
cloudreve    | [Panic]   2020-09-02 13:32:03 连接数据库不成功, unable to open database file
cloudreve    | panic: 连接数据库不成功, unable to open database file
cloudreve    |
cloudreve    | goroutine 1 [running]:
cloudreve    | github.com/HFO4/cloudreve/pkg/util.(*Logger).Panic(0xc0001d8730, 0x11dd06e, 0x1c, 0xc00031fe80, 0x1, 0x1)
cloudreve    |  /go/src/github.com/HFO4/cloudreve/pkg/util/logger.go:74 +0xe5
cloudreve    | github.com/HFO4/cloudreve/models.Init()
cloudreve    |  /go/src/github.com/HFO4/cloudreve/models/init.go:58 +0x345
cloudreve    | github.com/HFO4/cloudreve/bootstrap.Init(0x7fff619e0f6c, 0x15)
cloudreve    |  /go/src/github.com/HFO4/cloudreve/bootstrap/init.go:25 +0x86
cloudreve    | main.init.0()
cloudreve    |  /go/src/github.com/HFO4/cloudreve/main.go:20 +0x17a
```

### 2、复现步骤

使用以下配置启动 cloudreve(**先决条件: `/data/cloudreve.db` 不存在**)

```ini
; 数据库相关，如果你只想使用内置的 SQLite数据库，这一部分直接删去即可
[Database]
; 数据库类型，目前支持 sqlite | mysql
Type = sqlite3
; SQLite 数据库文件路径
DBFile = /data/cloudreve.db
```

**Comment by topjohncian** [comment]
Cloudreve所在的用户组是否能创建 `/data/cloudreve.db` ?

**Comment by mritd** [comment]
@topjohncian 不是权限问题，参考 PR #551 

默认情况下 Cloudreve 只判断了默认值 `UNSET`，其他情况直接 fmt 成数据库地址字符串，而 sqlite3 需要的是一个绝对文件路径，所以会出现问题。

**Comment by mritd** [comment]
代码在这个位置 https://github.com/cloudreve/Cloudreve/blob/master/models/init.go#L31 这里只判断了 UNSET，其他情况全部走标准的 Open 了

**Comment by topjohncian** [comment]
我懂力 刚开始没有理解错误

mritd <notifications@github.com> 于2020年9月2日周三 下午10:38写道：

**Comment by mritd** [comment]
😁 PR 里我把 err 判断也提上来了，因为如果 db open 出现 err，下面的 `db.LogMode(true)` 可能会空指针
