### ISSUE TITLE
postgresql 用户名配置不起作用

### ISSUE THREAD

**Issue by sb-child** [cloudreve/Cloudreve#991]
**Describe the bug**
postgresql 的用户名配置不起作用, 会使用当前登录的用户
类似: https://github.com/cloudreve/Cloudreve/issues/960

**To Reproduce**
1. 使用如下的配置文件, 启动 cloudreve
```
sbchild@server6:/mnt/m1/cr$ ./cloudreve
```
2. 崩溃

**Expected behavior**

**Screenshots**
配置文件
```ini
[System]
Mode = master
Listen = :5212
SessionSecret = xxx
HashIDSalt = xxx
[Redis]
Server = xxx
Password = xxx
DB = 0
[Database]
Type = postgres
Port = 5432 
User = cloudreve
Password = xxx
Host = 127.0.0.1
Name = cloudreve
TablePrefix = cd_
Charset = utf8
```
日志
```
   V3.3.2  Commit #db7489f  Pro=false
================================================

[Info]    2021-08-29 00:43:13 初始化数据库连接
[Panic]   2021-08-29 00:43:13 连接数据库不成功, pq: 用户 "sbchild" Password 认证失败
panic: 连接数据库不成功, pq: 用户 "sbchild" Password 认证失败

goroutine 1 [running]:
github.com/cloudreve/Cloudreve/v3/pkg/util.(*Logger).Panic(0xc0001e6fb0, 0x12b8b51, 0x1c, 0xc000409e20, 0x1, 0x1)
        /home/runner/work/Cloudreve/Cloudreve/pkg/util/logger.go:74 +0xe2
github.com/cloudreve/Cloudreve/v3/models.Init()
        /home/runner/work/Cloudreve/Cloudreve/models/init.go:53 +0x1ea
github.com/cloudreve/Cloudreve/v3/bootstrap.Init(0xc00021b0e0, 0x13)
        /home/runner/work/Cloudreve/Cloudreve/bootstrap/init.go:25 +0x85
main.init.0()
        /home/runner/work/Cloudreve/Cloudreve/main.go:23 +0x1f4
```

**Server**
 - OS: debian 10.10
 - Version V3.3.2 Commit #db7489f

**Comment by sb-child** [comment]
https://github.com/cloudreve/Cloudreve/pull/992
